name: vegan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.9
  - conda-forge::pymdown-extensions=8.1.1
  - bioconda::cyvcf2=0.30.6
  - conda-forge::pandas=1.2.3

  - bioconda::bwa=0.7.17  
  - bioconda::fastqc=0.11.8
  - bioconda::preseq=3.2.0
  - bioconda::samtools=1.15.1
  - bioconda::bcftools=1.15.1
  - bioconda::picard=2.27.4
  - bioconda::sambamba=0.7.1
  - bioconda::tabix=1.11
  - bioconda::multiqc=1.13
  - bioconda::bedtools=2.29.2
  - bioconda::mosdepth=0.3.1
  - bioconda::gatk4=4.2.6.1
  - bioconda::snpeff=5.1
  - bioconda::snpsift=5.1

  - conda-forge::r-base=4.1.3
  - conda-forge::r-data.table=1.14.2
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-ggplot2=3.3.6
  - conda-forge::r-rcolorbrewer=1.1_3
  - bioconda::ascat=2.5.2
  - bioconda::cancerit-allelecount=4.2.1

#
# Conflicts with MANTA which still require python2
#  - bioconda::manta=1.6.0

                                                                                                                                                                                   





