#
# VEGAN config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'
log_filesize_limit: 2000000000

###################################
## Custom content

custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ' of sequenced data. High (low)-quality alignments show the number of aligned reads with a mapping quality higher (lower) than 20. The fragment length, reads on target and mean sequencing depth are calculated after reads filtering.'
        plot_type: 'table'
        pconfig:
            namespace: 'stats'
            id: 'stats'
            title: 'General Statistics'
            save_file: true
            col1_header: 'Sample_ID'
        headers:
            Sample_name:
              title: 'Sample Name'
              scale: false
              format: '{:.0f}'
              placement: 1000
            Number_of_reads:
              title: 'Total Fragments'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              placement: 2000
            Fragment_length:
              title: 'Fragment Length'
              scale: 'YlGnGn'
              format: '{:,.0f}'
              placement: 3000
            Number_of_aligned_reads:
              title: 'Aligned Reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 3500
            Percent_of_aligned_reads:
              title: 'Aligned Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              suffix: '%'
              format: '{:,.1f}'
              placement: 4000
            Number_of_hq_mapped_reads:
              title: 'High-Quality Alignment'
              description: 'High-Quality Mapped Reads (mapQ > 20)'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 5000
            Percent_of_hq_mapped_reads:
              title: 'High-Quality Alignment (%)'
              description: 'High-Quality Mapped Reads (mapQ > 20)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 6000
            Number_of_lq_mapped_reads:
              title: 'Low-Quality Alignment'
              description: 'Low-Quality Mapped Reads (mapQ < 20)'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 7000
            Percent_of_lq_mapped_reads:
              title: 'Low-Quality Alignment (%)'
              description: 'Low-Quality Mapped Reads (mapQ < 20)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 8000
            Number_of_duplicates:
              title: 'Duplicates'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 9000
            Percent_of_duplicates:
              title: 'Duplicates (%)'
              min: 0
              max: 100
              scale: 'RdYlVBu'
              format: '{:,.1f}'
              suffix: '%'
              placement: 10000
            Number_reads_on_target:
              title: 'On Target'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 11000
            Percent_reads_on_target:
              title: 'On Target (%)'
              min: 0
              max: 100
              scale: 'RdYlVBu'
              format: '{:,.1f}'
              suffix: '%'
              placement: 12000
            Percent_of_overlap:
              title: 'Overlapping Bases (%)'
              description: 'In a read pair, reference bases covered by both R1 and R2'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 12500
            Mean_depth:
              title: 'Mean Depth'
              scale: 'RdYlGn'
              format: '{:,.1f}'
              placement: 13000
            30X_cov:
              title: '30X Coverage (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 14000
            80X_cov:
              title: '80X Coverage (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 15000

    bwa_logs:
        file_format: 'tsv'
        section_name: 'Bwa-mem'
        description: 'statistics on aligned data. Number of unique and multiple mapped reads, as well unmapped reads are reported.'
        plot_type: 'bargraph'
        pconfig:
            namespace: 'bwalogs'
            title: 'Reads Alignment'
            id: 'bwalogs'
            scale: 'Set1'
    genes_cov:
        file_format: 'tsv'
        section_name: 'Genes Coverage'
        description: 'distribution calculed from exonic regions overlapping the capture regions (if any).'
        plot_type: 'linegraph'
        pconfig:
            namescape: 'genescov'
            title: 'Genes Coverage'
            id: 'genescov'
            scale: 'Set1'
            ylab: 'Cumulative Genes Fraction (%)'
            xlab: 'Mean coverage (X)'
            xmax: 1000
    identito:
        file_format: 'csv'
        section_name: 'Identito Vigilance'
        description: 'heatmap is created from a defined list of SNPs. Using those SNPs, the similarity metric is calculated as 1- the Jaccard distance between all pairs of samples. Samples from the same patient are expected to have a high similarity score.'
        plot_type: 'heatmap'
        pconfig:
            title: 'Identito Vigilance heatmap'
            namescape: 'identito'
            id: 'identito'


sp:
  my_stats:
      fn: '*.stats'
  bwa_logs:
      fn: '*bwa.mqc'
  genes_cov:
      fn: '*covdensity.mqc'
  identito:
      fn: '*_identito.csv'

table_cond_formatting_rules:
    Percent_of_aligned_reads:
        pass:
          - gt: 80
        warn:
          - lt: 80
        fail:
          - lt: 50
    Percent_of_overlap:
        warn:
          - gt: 20
    Percent_of_duplicates:
        pass:
          - lt: 25
        warn:
          - gt: 25
        fail:
          - gt: 50
    Percent_reads_on_target:
        pass:
          - gt: 70
        warn:
          - lt: 70
        fail:
          - lt: 50
    Mean_depth:
        pass:
          - gt: 75
        warn:
          - lt: 75
        fail:
          - lt: 30
    Fragment_length:
        pass:
          - gt: 150
        warn:
          - lt: 150


###############################
## Modules

module_order:
  - fastqc
  - picard:
     name: 'Fragment Size'
  - mosdepth:
     name: 'Genome Coverage'
  - qualimap
  - gatk
  - bcftools
  - snpeff

report_section_order:
  my_stats:
    order: 1000
  fastqc:
    order: 900
  bwa_logs:
    order: 800
  picard:
    order: 600
  mosdepth:
    order: 500
  genes_cov:
    order: 300
  preseq:
    order: 200
  identito:
    order: 100
  software_versions:
    order: -2000
  summary:
    order: -2100


#############################
## Removed plots
remove_sections:
  - fastqc_sequence_counts
  - fastqc_per_sequence_quality_scores
  - fastqc_overrepresented_sequences
  - fastqc_status_checks
  - mosdepth-coverage-cov

fn_clean_exts:
    - '_bwa.log'
    - '_bwa.mqc'
    - '_covdensity.mqc'
    - '.filtered.SNV.txt'
    - '.filtered.SNV.bam'

plots_force_interactive: True
