#
# VEGAN config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'
log_filesize_limit: 2000000000

###################################
## Custom content

custom_data:
    bwa_logs:
        file_format: 'tsv'
        section_name: 'Bwa-mem'
        description: 'statistics on aligned data. Number of unique and multiple mapped reads, as well unmapped reads are reported.'
        plot_type: 'bargraph'
        pconfig:
            namespace: 'bwalogs'
            title: 'Reads Alignment'
            id: 'bwalogs'
            scale: 'Set1'

sp:
  my_stats:
      fn: '*.stats'
  bwa_logs:
      fn: '*bwa.mqc'


###############################
## Modules

module_order:
  - 'fastqc':
  - 'picard'
  - 'gatk'
  - 'qualimap'
  - 'bcftools'
  - 'snpeff'

#############################
## Removed plots
remove_sections :
  - fastqc_sequence_counts
  - fastqc_per_sequence_quality_scores
  - fastqc_overrepresented_sequences
  - fastqc_status_checks

fn_clean_exts:
    - '_bwa.log'
    - '_bwa.mqc'

plots_force_interactive: True